version: '3.9'
services:
  auth:
    build: ./auth/
    container_name: auth-app
    ports:
      - 8000:8000
    env_file:
      - ./auth/.env
  fetch:
    build: ./fetch/
    container_name: fetch-app
    ports:
      - 5000:5000
    env_file:
      - ./fetch/.env